# Generated by Django 4.0.5 on 2022-07-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='ip_address',
            field=models.TextField(max_length=100, null=True, verbose_name='Id'),
        ),
    ]
